provider: artifactory
major-version: 8
esc:
    enabled: true
env:
    ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
    ARTIFACTORY_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN}}
    PULUMI_MISSING_DOCS_ERROR: true
providerDefaultBranch: main
makeTemplate: bridged
pulumiConvert: 1
registryDocs: true
integrationTestProvider: true
