provider: artifactory
major-version: 8
esc:
    enabled: true
env:
    ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
    ARTIFACTORY_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN}}
    PULUMI_MISSING_DOCS_ERROR: true
providerDefaultBranch: main
makeTemplate: bridged
plugins:
    - name: terraform
      version: "1.0.16"
      kind: converter
    - name: random
      version: "4.3.1"
    - name: time
      version: "0.0.15"
    - name: std
      version: "1.6.2"
pulumiConvert: 1
registryDocs: true
integrationTestProvider: true
