// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Artifactory.Outputs
{

    [OutputType]
    public sealed class DockerWebhookCriteria
    {
        public readonly bool AnyLocal;
        public readonly bool AnyRemote;
        public readonly ImmutableArray<string> ExcludePatterns;
        public readonly ImmutableArray<string> IncludePatterns;
        public readonly ImmutableArray<string> RepoKeys;

        [OutputConstructor]
        private DockerWebhookCriteria(
            bool anyLocal,

            bool anyRemote,

            ImmutableArray<string> excludePatterns,

            ImmutableArray<string> includePatterns,

            ImmutableArray<string> repoKeys)
        {
            AnyLocal = anyLocal;
            AnyRemote = anyRemote;
            ExcludePatterns = excludePatterns;
            IncludePatterns = includePatterns;
            RepoKeys = repoKeys;
        }
    }
}
