// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.artifactory;

import com.pulumi.artifactory.ReleaseBundleV2PromotionCustomWebhookArgs;
import com.pulumi.artifactory.Utilities;
import com.pulumi.artifactory.inputs.ReleaseBundleV2PromotionCustomWebhookState;
import com.pulumi.artifactory.outputs.ReleaseBundleV2PromotionCustomWebhookCriteria;
import com.pulumi.artifactory.outputs.ReleaseBundleV2PromotionCustomWebhookHandler;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Provides an Artifactory custom webhook resource. This can be used to register and manage Artifactory webhook subscription which enables you to be notified or notify other users when such events take place in Artifactory.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.artifactory.ReleaseBundleV2PromotionCustomWebhook;
 * import com.pulumi.artifactory.ReleaseBundleV2PromotionCustomWebhookArgs;
 * import com.pulumi.artifactory.inputs.ReleaseBundleV2PromotionCustomWebhookCriteriaArgs;
 * import com.pulumi.artifactory.inputs.ReleaseBundleV2PromotionCustomWebhookHandlerArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var release_bundle_v2_promotion_custom_webhook = new ReleaseBundleV2PromotionCustomWebhook("release-bundle-v2-promotion-custom-webhook", ReleaseBundleV2PromotionCustomWebhookArgs.builder()
 *             .key("release-bundle-custom-webhook")
 *             .eventTypes(            
 *                 "release_bundle_v2_promotion_completed",
 *                 "release_bundle_v2_promotion_failed",
 *                 "release_bundle_v2_promotion_started")
 *             .criteria(ReleaseBundleV2PromotionCustomWebhookCriteriaArgs.builder()
 *                 .selectedEnvironments(                
 *                     "PROD",
 *                     "DEV")
 *                 .build())
 *             .handlers(ReleaseBundleV2PromotionCustomWebhookHandlerArgs.builder()
 *                 .url("https://tempurl.org")
 *                 .method("POST")
 *                 .secrets(Map.ofEntries(
 *                     Map.entry("secretName1", "value1"),
 *                     Map.entry("secretName2", "value2")
 *                 ))
 *                 .httpHeaders(Map.ofEntries(
 *                     Map.entry("headerName1", "value1"),
 *                     Map.entry("headerName2", "value2")
 *                 ))
 *                 .payload("{ \"ref\": \"main\" , \"inputs\": { \"artifact_path\": \"test-repo/repo-path\" } }")
 *                 .build())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 */
@ResourceType(type="artifactory:index/releaseBundleV2PromotionCustomWebhook:ReleaseBundleV2PromotionCustomWebhook")
public class ReleaseBundleV2PromotionCustomWebhook extends com.pulumi.resources.CustomResource {
    /**
     * Specifies where the webhook will be applied on which enviroments.
     * 
     */
    @Export(name="criteria", refs={ReleaseBundleV2PromotionCustomWebhookCriteria.class}, tree="[0]")
    private Output</* @Nullable */ ReleaseBundleV2PromotionCustomWebhookCriteria> criteria;

    /**
     * @return Specifies where the webhook will be applied on which enviroments.
     * 
     */
    public Output<Optional<ReleaseBundleV2PromotionCustomWebhookCriteria>> criteria() {
        return Codegen.optional(this.criteria);
    }
    /**
     * Webhook description. Max length 1000 characters.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return Webhook description. Max length 1000 characters.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * Status of webhook. Default to `true`.
     * 
     */
    @Export(name="enabled", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> enabled;

    /**
     * @return Status of webhook. Default to `true`.
     * 
     */
    public Output<Boolean> enabled() {
        return this.enabled;
    }
    /**
     * List of event triggers for the Webhook. Allow values: `release_bundle_v2_promotion_started`, `release_bundle_v2_promotion_completed`, `release_bundle_v2_promotion_failed`
     * 
     */
    @Export(name="eventTypes", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> eventTypes;

    /**
     * @return List of event triggers for the Webhook. Allow values: `release_bundle_v2_promotion_started`, `release_bundle_v2_promotion_completed`, `release_bundle_v2_promotion_failed`
     * 
     */
    public Output<List<String>> eventTypes() {
        return this.eventTypes;
    }
    /**
     * At least one is required.
     * 
     */
    @Export(name="handlers", refs={List.class,ReleaseBundleV2PromotionCustomWebhookHandler.class}, tree="[0,1]")
    private Output</* @Nullable */ List<ReleaseBundleV2PromotionCustomWebhookHandler>> handlers;

    /**
     * @return At least one is required.
     * 
     */
    public Output<Optional<List<ReleaseBundleV2PromotionCustomWebhookHandler>>> handlers() {
        return Codegen.optional(this.handlers);
    }
    /**
     * The identity key of the webhook. Must be between 2 and 200 characters. Cannot contain spaces.
     * 
     */
    @Export(name="key", refs={String.class}, tree="[0]")
    private Output<String> key;

    /**
     * @return The identity key of the webhook. Must be between 2 and 200 characters. Cannot contain spaces.
     * 
     */
    public Output<String> key() {
        return this.key;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ReleaseBundleV2PromotionCustomWebhook(java.lang.String name) {
        this(name, ReleaseBundleV2PromotionCustomWebhookArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ReleaseBundleV2PromotionCustomWebhook(java.lang.String name, ReleaseBundleV2PromotionCustomWebhookArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ReleaseBundleV2PromotionCustomWebhook(java.lang.String name, ReleaseBundleV2PromotionCustomWebhookArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("artifactory:index/releaseBundleV2PromotionCustomWebhook:ReleaseBundleV2PromotionCustomWebhook", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private ReleaseBundleV2PromotionCustomWebhook(java.lang.String name, Output<java.lang.String> id, @Nullable ReleaseBundleV2PromotionCustomWebhookState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("artifactory:index/releaseBundleV2PromotionCustomWebhook:ReleaseBundleV2PromotionCustomWebhook", name, state, makeResourceOptions(options, id), false);
    }

    private static ReleaseBundleV2PromotionCustomWebhookArgs makeArgs(ReleaseBundleV2PromotionCustomWebhookArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ReleaseBundleV2PromotionCustomWebhookArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ReleaseBundleV2PromotionCustomWebhook get(java.lang.String name, Output<java.lang.String> id, @Nullable ReleaseBundleV2PromotionCustomWebhookState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ReleaseBundleV2PromotionCustomWebhook(name, id, state, options);
    }
}
