// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.artifactory;

import com.pulumi.artifactory.ReleaseBundleV2PromotionWebhookArgs;
import com.pulumi.artifactory.Utilities;
import com.pulumi.artifactory.inputs.ReleaseBundleV2PromotionWebhookState;
import com.pulumi.artifactory.outputs.ReleaseBundleV2PromotionWebhookCriteria;
import com.pulumi.artifactory.outputs.ReleaseBundleV2PromotionWebhookHandler;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Provides an Artifactory webhook resource. This can be used to register and manage Artifactory webhook subscription which enables you to be notified or notify other users when such events take place in Artifactory.
 * 
 * ## Example Usage
 * 
 * .
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.artifactory.ReleaseBundleV2PromotionWebhook;
 * import com.pulumi.artifactory.ReleaseBundleV2PromotionWebhookArgs;
 * import com.pulumi.artifactory.inputs.ReleaseBundleV2PromotionWebhookCriteriaArgs;
 * import com.pulumi.artifactory.inputs.ReleaseBundleV2PromotionWebhookHandlerArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var release_bundle_v2_promotion_webhook = new ReleaseBundleV2PromotionWebhook("release-bundle-v2-promotion-webhook", ReleaseBundleV2PromotionWebhookArgs.builder()
 *             .key("release-bundle-v2-promotion-webhook")
 *             .eventTypes(            
 *                 "release_bundle_v2_promotion_completed",
 *                 "release_bundle_v2_promotion_failed",
 *                 "release_bundle_v2_promotion_started")
 *             .criteria(ReleaseBundleV2PromotionWebhookCriteriaArgs.builder()
 *                 .selectedEnvironments(                
 *                     "PROD",
 *                     "DEV")
 *                 .build())
 *             .handlers(ReleaseBundleV2PromotionWebhookHandlerArgs.builder()
 *                 .url("http://tempurl.org/webhook")
 *                 .secret("some-secret")
 *                 .proxy("proxy-key")
 *                 .customHttpHeaders(Map.ofEntries(
 *                     Map.entry("header-1", "value-1"),
 *                     Map.entry("header-2", "value-2")
 *                 ))
 *                 .build())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 */
@ResourceType(type="artifactory:index/releaseBundleV2PromotionWebhook:ReleaseBundleV2PromotionWebhook")
public class ReleaseBundleV2PromotionWebhook extends com.pulumi.resources.CustomResource {
    /**
     * Specifies where the webhook will be applied on which enviroments.
     * 
     */
    @Export(name="criteria", refs={ReleaseBundleV2PromotionWebhookCriteria.class}, tree="[0]")
    private Output</* @Nullable */ ReleaseBundleV2PromotionWebhookCriteria> criteria;

    /**
     * @return Specifies where the webhook will be applied on which enviroments.
     * 
     */
    public Output<Optional<ReleaseBundleV2PromotionWebhookCriteria>> criteria() {
        return Codegen.optional(this.criteria);
    }
    /**
     * Webhook description. Max length 1000 characters.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return Webhook description. Max length 1000 characters.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * Status of webhook. Default to `true`
     * 
     */
    @Export(name="enabled", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> enabled;

    /**
     * @return Status of webhook. Default to `true`
     * 
     */
    public Output<Boolean> enabled() {
        return this.enabled;
    }
    /**
     * List of event triggers for the Webhook. Allow values: `releaseBundleV2PromotionStarted`, `releaseBundleV2PromotionCompleted`, `releaseBundleV2PromotionFailed`
     * 
     */
    @Export(name="eventTypes", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> eventTypes;

    /**
     * @return List of event triggers for the Webhook. Allow values: `releaseBundleV2PromotionStarted`, `releaseBundleV2PromotionCompleted`, `releaseBundleV2PromotionFailed`
     * 
     */
    public Output<List<String>> eventTypes() {
        return this.eventTypes;
    }
    /**
     * At least one is required.
     * 
     */
    @Export(name="handlers", refs={List.class,ReleaseBundleV2PromotionWebhookHandler.class}, tree="[0,1]")
    private Output</* @Nullable */ List<ReleaseBundleV2PromotionWebhookHandler>> handlers;

    /**
     * @return At least one is required.
     * 
     */
    public Output<Optional<List<ReleaseBundleV2PromotionWebhookHandler>>> handlers() {
        return Codegen.optional(this.handlers);
    }
    /**
     * The identity key of the webhook. Must be between 2 and 200 characters. Cannot contain spaces.
     * 
     */
    @Export(name="key", refs={String.class}, tree="[0]")
    private Output<String> key;

    /**
     * @return The identity key of the webhook. Must be between 2 and 200 characters. Cannot contain spaces.
     * 
     */
    public Output<String> key() {
        return this.key;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ReleaseBundleV2PromotionWebhook(java.lang.String name) {
        this(name, ReleaseBundleV2PromotionWebhookArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ReleaseBundleV2PromotionWebhook(java.lang.String name, ReleaseBundleV2PromotionWebhookArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ReleaseBundleV2PromotionWebhook(java.lang.String name, ReleaseBundleV2PromotionWebhookArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("artifactory:index/releaseBundleV2PromotionWebhook:ReleaseBundleV2PromotionWebhook", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private ReleaseBundleV2PromotionWebhook(java.lang.String name, Output<java.lang.String> id, @Nullable ReleaseBundleV2PromotionWebhookState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("artifactory:index/releaseBundleV2PromotionWebhook:ReleaseBundleV2PromotionWebhook", name, state, makeResourceOptions(options, id), false);
    }

    private static ReleaseBundleV2PromotionWebhookArgs makeArgs(ReleaseBundleV2PromotionWebhookArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ReleaseBundleV2PromotionWebhookArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ReleaseBundleV2PromotionWebhook get(java.lang.String name, Output<java.lang.String> id, @Nullable ReleaseBundleV2PromotionWebhookState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ReleaseBundleV2PromotionWebhook(name, id, state, options);
    }
}
