// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.artifactory.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetRepositoriesRepo {
    private String description;
    private String key;
    private String packageType;
    private String type;
    private String url;

    private GetRepositoriesRepo() {}
    public String description() {
        return this.description;
    }
    public String key() {
        return this.key;
    }
    public String packageType() {
        return this.packageType;
    }
    public String type() {
        return this.type;
    }
    public String url() {
        return this.url;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetRepositoriesRepo defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String description;
        private String key;
        private String packageType;
        private String type;
        private String url;
        public Builder() {}
        public Builder(GetRepositoriesRepo defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.description = defaults.description;
    	      this.key = defaults.key;
    	      this.packageType = defaults.packageType;
    	      this.type = defaults.type;
    	      this.url = defaults.url;
        }

        @CustomType.Setter
        public Builder description(String description) {
            this.description = Objects.requireNonNull(description);
            return this;
        }
        @CustomType.Setter
        public Builder key(String key) {
            this.key = Objects.requireNonNull(key);
            return this;
        }
        @CustomType.Setter
        public Builder packageType(String packageType) {
            this.packageType = Objects.requireNonNull(packageType);
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }
        @CustomType.Setter
        public Builder url(String url) {
            this.url = Objects.requireNonNull(url);
            return this;
        }
        public GetRepositoriesRepo build() {
            final var _resultValue = new GetRepositoriesRepo();
            _resultValue.description = description;
            _resultValue.key = key;
            _resultValue.packageType = packageType;
            _resultValue.type = type;
            _resultValue.url = url;
            return _resultValue;
        }
    }
}
