// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.artifactory.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class OauthSettingsOauthProvider {
    private String apiUrl;
    private String authUrl;
    private String clientId;
    private String clientSecret;
    private @Nullable Boolean enabled;
    private String name;
    private String tokenUrl;
    private String type;

    private OauthSettingsOauthProvider() {}
    public String apiUrl() {
        return this.apiUrl;
    }
    public String authUrl() {
        return this.authUrl;
    }
    public String clientId() {
        return this.clientId;
    }
    public String clientSecret() {
        return this.clientSecret;
    }
    public Optional<Boolean> enabled() {
        return Optional.ofNullable(this.enabled);
    }
    public String name() {
        return this.name;
    }
    public String tokenUrl() {
        return this.tokenUrl;
    }
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(OauthSettingsOauthProvider defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String apiUrl;
        private String authUrl;
        private String clientId;
        private String clientSecret;
        private @Nullable Boolean enabled;
        private String name;
        private String tokenUrl;
        private String type;
        public Builder() {}
        public Builder(OauthSettingsOauthProvider defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.apiUrl = defaults.apiUrl;
    	      this.authUrl = defaults.authUrl;
    	      this.clientId = defaults.clientId;
    	      this.clientSecret = defaults.clientSecret;
    	      this.enabled = defaults.enabled;
    	      this.name = defaults.name;
    	      this.tokenUrl = defaults.tokenUrl;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder apiUrl(String apiUrl) {
            this.apiUrl = Objects.requireNonNull(apiUrl);
            return this;
        }
        @CustomType.Setter
        public Builder authUrl(String authUrl) {
            this.authUrl = Objects.requireNonNull(authUrl);
            return this;
        }
        @CustomType.Setter
        public Builder clientId(String clientId) {
            this.clientId = Objects.requireNonNull(clientId);
            return this;
        }
        @CustomType.Setter
        public Builder clientSecret(String clientSecret) {
            this.clientSecret = Objects.requireNonNull(clientSecret);
            return this;
        }
        @CustomType.Setter
        public Builder enabled(@Nullable Boolean enabled) {
            this.enabled = enabled;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        @CustomType.Setter
        public Builder tokenUrl(String tokenUrl) {
            this.tokenUrl = Objects.requireNonNull(tokenUrl);
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }
        public OauthSettingsOauthProvider build() {
            final var o = new OauthSettingsOauthProvider();
            o.apiUrl = apiUrl;
            o.authUrl = authUrl;
            o.clientId = clientId;
            o.clientSecret = clientSecret;
            o.enabled = enabled;
            o.name = name;
            o.tokenUrl = tokenUrl;
            o.type = type;
            return o;
        }
    }
}
