// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.artifactory.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetFileinfoArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetFileinfoArgs Empty = new GetFileinfoArgs();

    /**
     * The path to the file within the repository.
     * 
     */
    @Import(name="path", required=true)
    private Output<String> path;

    /**
     * @return The path to the file within the repository.
     * 
     */
    public Output<String> path() {
        return this.path;
    }

    /**
     * Name of the repository where the file is stored.
     * 
     */
    @Import(name="repository", required=true)
    private Output<String> repository;

    /**
     * @return Name of the repository where the file is stored.
     * 
     */
    public Output<String> repository() {
        return this.repository;
    }

    private GetFileinfoArgs() {}

    private GetFileinfoArgs(GetFileinfoArgs $) {
        this.path = $.path;
        this.repository = $.repository;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetFileinfoArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetFileinfoArgs $;

        public Builder() {
            $ = new GetFileinfoArgs();
        }

        public Builder(GetFileinfoArgs defaults) {
            $ = new GetFileinfoArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param path The path to the file within the repository.
         * 
         * @return builder
         * 
         */
        public Builder path(Output<String> path) {
            $.path = path;
            return this;
        }

        /**
         * @param path The path to the file within the repository.
         * 
         * @return builder
         * 
         */
        public Builder path(String path) {
            return path(Output.of(path));
        }

        /**
         * @param repository Name of the repository where the file is stored.
         * 
         * @return builder
         * 
         */
        public Builder repository(Output<String> repository) {
            $.repository = repository;
            return this;
        }

        /**
         * @param repository Name of the repository where the file is stored.
         * 
         * @return builder
         * 
         */
        public Builder repository(String repository) {
            return repository(Output.of(repository));
        }

        public GetFileinfoArgs build() {
            if ($.path == null) {
                throw new MissingRequiredPropertyException("GetFileinfoArgs", "path");
            }
            if ($.repository == null) {
                throw new MissingRequiredPropertyException("GetFileinfoArgs", "repository");
            }
            return $;
        }
    }

}
