// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.artifactory.inputs;

import com.pulumi.artifactory.inputs.GetPermissionTargetReleaseBundleActions;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetPermissionTargetReleaseBundle extends com.pulumi.resources.InvokeArgs {

    public static final GetPermissionTargetReleaseBundle Empty = new GetPermissionTargetReleaseBundle();

    @Import(name="actions")
    private @Nullable GetPermissionTargetReleaseBundleActions actions;

    public Optional<GetPermissionTargetReleaseBundleActions> actions() {
        return Optional.ofNullable(this.actions);
    }

    @Import(name="excludesPatterns")
    private @Nullable List<String> excludesPatterns;

    public Optional<List<String>> excludesPatterns() {
        return Optional.ofNullable(this.excludesPatterns);
    }

    @Import(name="includesPatterns")
    private @Nullable List<String> includesPatterns;

    public Optional<List<String>> includesPatterns() {
        return Optional.ofNullable(this.includesPatterns);
    }

    @Import(name="repositories", required=true)
    private List<String> repositories;

    public List<String> repositories() {
        return this.repositories;
    }

    private GetPermissionTargetReleaseBundle() {}

    private GetPermissionTargetReleaseBundle(GetPermissionTargetReleaseBundle $) {
        this.actions = $.actions;
        this.excludesPatterns = $.excludesPatterns;
        this.includesPatterns = $.includesPatterns;
        this.repositories = $.repositories;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetPermissionTargetReleaseBundle defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetPermissionTargetReleaseBundle $;

        public Builder() {
            $ = new GetPermissionTargetReleaseBundle();
        }

        public Builder(GetPermissionTargetReleaseBundle defaults) {
            $ = new GetPermissionTargetReleaseBundle(Objects.requireNonNull(defaults));
        }

        public Builder actions(@Nullable GetPermissionTargetReleaseBundleActions actions) {
            $.actions = actions;
            return this;
        }

        public Builder excludesPatterns(@Nullable List<String> excludesPatterns) {
            $.excludesPatterns = excludesPatterns;
            return this;
        }

        public Builder excludesPatterns(String... excludesPatterns) {
            return excludesPatterns(List.of(excludesPatterns));
        }

        public Builder includesPatterns(@Nullable List<String> includesPatterns) {
            $.includesPatterns = includesPatterns;
            return this;
        }

        public Builder includesPatterns(String... includesPatterns) {
            return includesPatterns(List.of(includesPatterns));
        }

        public Builder repositories(List<String> repositories) {
            $.repositories = repositories;
            return this;
        }

        public Builder repositories(String... repositories) {
            return repositories(List.of(repositories));
        }

        public GetPermissionTargetReleaseBundle build() {
            $.repositories = Objects.requireNonNull($.repositories, "expected parameter 'repositories' to be non-null");
            return $;
        }
    }

}
