// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.artifactory.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetVirtualHexRepositoryPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetVirtualHexRepositoryPlainArgs Empty = new GetVirtualHexRepositoryPlainArgs();

    /**
     * the identity key of the repo.
     * 
     */
    @Import(name="key", required=true)
    private String key;

    /**
     * @return the identity key of the repo.
     * 
     */
    public String key() {
        return this.key;
    }

    private GetVirtualHexRepositoryPlainArgs() {}

    private GetVirtualHexRepositoryPlainArgs(GetVirtualHexRepositoryPlainArgs $) {
        this.key = $.key;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetVirtualHexRepositoryPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetVirtualHexRepositoryPlainArgs $;

        public Builder() {
            $ = new GetVirtualHexRepositoryPlainArgs();
        }

        public Builder(GetVirtualHexRepositoryPlainArgs defaults) {
            $ = new GetVirtualHexRepositoryPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param key the identity key of the repo.
         * 
         * @return builder
         * 
         */
        public Builder key(String key) {
            $.key = key;
            return this;
        }

        public GetVirtualHexRepositoryPlainArgs build() {
            if ($.key == null) {
                throw new MissingRequiredPropertyException("GetVirtualHexRepositoryPlainArgs", "key");
            }
            return $;
        }
    }

}
