// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Provides an Artifactory LDAP Setting resource.
 *
 * This resource can be used to manage Artifactory's LDAP Group settings for user authentication.
 *
 * LDAP Groups Add-on allows you to synchronize your LDAP groups with the system and leverage your existing organizational
 * structure for managing group-based permissions.
 *
 * [API documentation](https://jfrog.com/help/r/jfrog-rest-apis/ldap-group-setting), [general documentation](https://jfrog.com/help/r/jfrog-platform-administration-documentation/ldap).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as artifactory from "@pulumi/artifactory";
 *
 * const ldapGroupName = new artifactory.LdapGroupSettingV2("ldapGroupName", {
 *     descriptionAttribute: "description",
 *     enabledLdap: "ldap_name",
 *     filter: "(objectClass=groupOfNames)",
 *     forceAttributeSearch: false,
 *     groupBaseDn: "CN=Users,DC=MyDomain,DC=com",
 *     groupMemberAttribute: "uniqueMember",
 *     groupNameAttribute: "cn",
 *     strategy: "STATIC",
 *     subTree: true,
 * });
 * ```
 *
 * ## Import
 *
 * ```sh
 *  $ pulumi import artifactory:index/ldapGroupSettingV2:LdapGroupSettingV2 ldap ldapGroup1
 * ```
 */
export class LdapGroupSettingV2 extends pulumi.CustomResource {
    /**
     * Get an existing LdapGroupSettingV2 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LdapGroupSettingV2State, opts?: pulumi.CustomResourceOptions): LdapGroupSettingV2 {
        return new LdapGroupSettingV2(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'artifactory:index/ldapGroupSettingV2:LdapGroupSettingV2';

    /**
     * Returns true if the given object is an instance of LdapGroupSettingV2.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is LdapGroupSettingV2 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LdapGroupSettingV2.__pulumiType;
    }

    /**
     * An attribute on the group entry which denoting the group description. Used when importing groups.
     */
    public readonly descriptionAttribute!: pulumi.Output<string>;
    /**
     * The LDAP setting key you want to use for group retrieval.
     */
    public readonly enabledLdap!: pulumi.Output<string>;
    /**
     * The LDAP filter used to search for group entries. Used for importing groups.
     */
    public readonly filter!: pulumi.Output<string>;
    /**
     * This attribute is used in very specific cases of LDAP group settings. Don't switch it to `false`, unless instructed by the JFrog support team. Default value is `false`.
     */
    public readonly forceAttributeSearch!: pulumi.Output<boolean>;
    /**
     * A search base for group entry DNs, relative to the DN on the LDAP server’s URL (and not relative to the LDAP Setting’s “Search Base”). Used when importing groups.
     */
    public readonly groupBaseDn!: pulumi.Output<string>;
    /**
     * A multi-value attribute on the group entry containing user DNs or IDs of the group members (e.g., uniqueMember, member).
     */
    public readonly groupMemberAttribute!: pulumi.Output<string>;
    /**
     * Attribute on the group entry denoting the group name. Used when importing groups.
     */
    public readonly groupNameAttribute!: pulumi.Output<string>;
    /**
     * Ldap group setting name.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The JFrog Platform Deployment (JPD) supports three ways of mapping groups to LDAP schemas: STATIC: Group objects are aware of their members, however, the users are not aware of the groups they belong to. Each group object such as groupOfNames or groupOfUniqueNames holds its respective member attributes, typically member or uniqueMember, which is a user DN. DYNAMIC: User objects are aware of what groups they belong to, but the group objects are not aware of their members. Each user object contains a custom attribute, such as group, that holds the group DNs or group names of which the user is a member. HIERARCHICAL: The user's DN is indicative of the groups the user belongs to by using group names as part of user DN hierarchy. Each user DN contains a list of ou's or custom attributes that make up the group association. For example, `uid=user1,ou=developers,ou=uk,dc=jfrog,dc=org` indicates that `user1` belongs to two groups: `uk` and `developers`. Valid values are: `STATIC`, `DYNAMIC`, `HIERARCHICAL`, case sensitive, all caps.
     */
    public readonly strategy!: pulumi.Output<string>;
    /**
     * When set, enables deep search through the sub-tree of the LDAP URL + Search Base. `true` by default. `subTree` can be set to true only with `STATIC` or `DYNAMIC` strategy.
     */
    public readonly subTree!: pulumi.Output<boolean>;

    /**
     * Create a LdapGroupSettingV2 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LdapGroupSettingV2Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: LdapGroupSettingV2Args | LdapGroupSettingV2State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as LdapGroupSettingV2State | undefined;
            resourceInputs["descriptionAttribute"] = state ? state.descriptionAttribute : undefined;
            resourceInputs["enabledLdap"] = state ? state.enabledLdap : undefined;
            resourceInputs["filter"] = state ? state.filter : undefined;
            resourceInputs["forceAttributeSearch"] = state ? state.forceAttributeSearch : undefined;
            resourceInputs["groupBaseDn"] = state ? state.groupBaseDn : undefined;
            resourceInputs["groupMemberAttribute"] = state ? state.groupMemberAttribute : undefined;
            resourceInputs["groupNameAttribute"] = state ? state.groupNameAttribute : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["strategy"] = state ? state.strategy : undefined;
            resourceInputs["subTree"] = state ? state.subTree : undefined;
        } else {
            const args = argsOrState as LdapGroupSettingV2Args | undefined;
            if ((!args || args.descriptionAttribute === undefined) && !opts.urn) {
                throw new Error("Missing required property 'descriptionAttribute'");
            }
            if ((!args || args.filter === undefined) && !opts.urn) {
                throw new Error("Missing required property 'filter'");
            }
            if ((!args || args.groupMemberAttribute === undefined) && !opts.urn) {
                throw new Error("Missing required property 'groupMemberAttribute'");
            }
            if ((!args || args.groupNameAttribute === undefined) && !opts.urn) {
                throw new Error("Missing required property 'groupNameAttribute'");
            }
            if ((!args || args.strategy === undefined) && !opts.urn) {
                throw new Error("Missing required property 'strategy'");
            }
            resourceInputs["descriptionAttribute"] = args ? args.descriptionAttribute : undefined;
            resourceInputs["enabledLdap"] = args ? args.enabledLdap : undefined;
            resourceInputs["filter"] = args ? args.filter : undefined;
            resourceInputs["forceAttributeSearch"] = args ? args.forceAttributeSearch : undefined;
            resourceInputs["groupBaseDn"] = args ? args.groupBaseDn : undefined;
            resourceInputs["groupMemberAttribute"] = args ? args.groupMemberAttribute : undefined;
            resourceInputs["groupNameAttribute"] = args ? args.groupNameAttribute : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["strategy"] = args ? args.strategy : undefined;
            resourceInputs["subTree"] = args ? args.subTree : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(LdapGroupSettingV2.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering LdapGroupSettingV2 resources.
 */
export interface LdapGroupSettingV2State {
    /**
     * An attribute on the group entry which denoting the group description. Used when importing groups.
     */
    descriptionAttribute?: pulumi.Input<string>;
    /**
     * The LDAP setting key you want to use for group retrieval.
     */
    enabledLdap?: pulumi.Input<string>;
    /**
     * The LDAP filter used to search for group entries. Used for importing groups.
     */
    filter?: pulumi.Input<string>;
    /**
     * This attribute is used in very specific cases of LDAP group settings. Don't switch it to `false`, unless instructed by the JFrog support team. Default value is `false`.
     */
    forceAttributeSearch?: pulumi.Input<boolean>;
    /**
     * A search base for group entry DNs, relative to the DN on the LDAP server’s URL (and not relative to the LDAP Setting’s “Search Base”). Used when importing groups.
     */
    groupBaseDn?: pulumi.Input<string>;
    /**
     * A multi-value attribute on the group entry containing user DNs or IDs of the group members (e.g., uniqueMember, member).
     */
    groupMemberAttribute?: pulumi.Input<string>;
    /**
     * Attribute on the group entry denoting the group name. Used when importing groups.
     */
    groupNameAttribute?: pulumi.Input<string>;
    /**
     * Ldap group setting name.
     */
    name?: pulumi.Input<string>;
    /**
     * The JFrog Platform Deployment (JPD) supports three ways of mapping groups to LDAP schemas: STATIC: Group objects are aware of their members, however, the users are not aware of the groups they belong to. Each group object such as groupOfNames or groupOfUniqueNames holds its respective member attributes, typically member or uniqueMember, which is a user DN. DYNAMIC: User objects are aware of what groups they belong to, but the group objects are not aware of their members. Each user object contains a custom attribute, such as group, that holds the group DNs or group names of which the user is a member. HIERARCHICAL: The user's DN is indicative of the groups the user belongs to by using group names as part of user DN hierarchy. Each user DN contains a list of ou's or custom attributes that make up the group association. For example, `uid=user1,ou=developers,ou=uk,dc=jfrog,dc=org` indicates that `user1` belongs to two groups: `uk` and `developers`. Valid values are: `STATIC`, `DYNAMIC`, `HIERARCHICAL`, case sensitive, all caps.
     */
    strategy?: pulumi.Input<string>;
    /**
     * When set, enables deep search through the sub-tree of the LDAP URL + Search Base. `true` by default. `subTree` can be set to true only with `STATIC` or `DYNAMIC` strategy.
     */
    subTree?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a LdapGroupSettingV2 resource.
 */
export interface LdapGroupSettingV2Args {
    /**
     * An attribute on the group entry which denoting the group description. Used when importing groups.
     */
    descriptionAttribute: pulumi.Input<string>;
    /**
     * The LDAP setting key you want to use for group retrieval.
     */
    enabledLdap?: pulumi.Input<string>;
    /**
     * The LDAP filter used to search for group entries. Used for importing groups.
     */
    filter: pulumi.Input<string>;
    /**
     * This attribute is used in very specific cases of LDAP group settings. Don't switch it to `false`, unless instructed by the JFrog support team. Default value is `false`.
     */
    forceAttributeSearch?: pulumi.Input<boolean>;
    /**
     * A search base for group entry DNs, relative to the DN on the LDAP server’s URL (and not relative to the LDAP Setting’s “Search Base”). Used when importing groups.
     */
    groupBaseDn?: pulumi.Input<string>;
    /**
     * A multi-value attribute on the group entry containing user DNs or IDs of the group members (e.g., uniqueMember, member).
     */
    groupMemberAttribute: pulumi.Input<string>;
    /**
     * Attribute on the group entry denoting the group name. Used when importing groups.
     */
    groupNameAttribute: pulumi.Input<string>;
    /**
     * Ldap group setting name.
     */
    name?: pulumi.Input<string>;
    /**
     * The JFrog Platform Deployment (JPD) supports three ways of mapping groups to LDAP schemas: STATIC: Group objects are aware of their members, however, the users are not aware of the groups they belong to. Each group object such as groupOfNames or groupOfUniqueNames holds its respective member attributes, typically member or uniqueMember, which is a user DN. DYNAMIC: User objects are aware of what groups they belong to, but the group objects are not aware of their members. Each user object contains a custom attribute, such as group, that holds the group DNs or group names of which the user is a member. HIERARCHICAL: The user's DN is indicative of the groups the user belongs to by using group names as part of user DN hierarchy. Each user DN contains a list of ou's or custom attributes that make up the group association. For example, `uid=user1,ou=developers,ou=uk,dc=jfrog,dc=org` indicates that `user1` belongs to two groups: `uk` and `developers`. Valid values are: `STATIC`, `DYNAMIC`, `HIERARCHICAL`, case sensitive, all caps.
     */
    strategy: pulumi.Input<string>;
    /**
     * When set, enables deep search through the sub-tree of the LDAP URL + Search Base. `true` by default. `subTree` can be set to true only with `STATIC` or `DYNAMIC` strategy.
     */
    subTree?: pulumi.Input<boolean>;
}
