// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## # Artifactory Local Repository Resource
 *
 * Provides an Artifactory local repository resource. This can be used to create and manage Artifactory local repositories.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as artifactory from "@pulumi/artifactory";
 *
 * // Create a new Artifactory local repository called my-local
 * const my_local = new artifactory.LocalRepository("my-local", {
 *     key: "my-local",
 *     packageType: "npm",
 * });
 * ```
 *
 * ## Import
 *
 * Local repositories can be imported using their name, e.g.
 *
 * ```sh
 *  $ pulumi import artifactory:index/localRepository:LocalRepository my-local my-local
 * ```
 */
export class LocalRepository extends pulumi.CustomResource {
    /**
     * Get an existing LocalRepository resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LocalRepositoryState, opts?: pulumi.CustomResourceOptions): LocalRepository {
        return new LocalRepository(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'artifactory:index/localRepository:LocalRepository';

    /**
     * Returns true if the given object is an instance of LocalRepository.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is LocalRepository {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LocalRepository.__pulumiType;
    }

    public readonly archiveBrowsingEnabled!: pulumi.Output<boolean | undefined>;
    public readonly blackedOut!: pulumi.Output<boolean>;
    public readonly calculateYumMetadata!: pulumi.Output<boolean | undefined>;
    public readonly checksumPolicyType!: pulumi.Output<string>;
    public readonly debianTrivialLayout!: pulumi.Output<boolean | undefined>;
    public readonly description!: pulumi.Output<string | undefined>;
    public readonly dockerApiVersion!: pulumi.Output<string>;
    public readonly enableFileListsIndexing!: pulumi.Output<boolean>;
    public readonly excludesPattern!: pulumi.Output<string>;
    public readonly forceNugetAuthentication!: pulumi.Output<boolean>;
    public readonly handleReleases!: pulumi.Output<boolean>;
    public readonly handleSnapshots!: pulumi.Output<boolean>;
    public readonly includesPattern!: pulumi.Output<string>;
    public readonly indexCompressionFormats!: pulumi.Output<string[] | undefined>;
    public readonly key!: pulumi.Output<string>;
    public readonly maxUniqueSnapshots!: pulumi.Output<number>;
    public readonly maxUniqueTags!: pulumi.Output<number>;
    public readonly notes!: pulumi.Output<string | undefined>;
    public readonly packageType!: pulumi.Output<string>;
    public readonly propertySets!: pulumi.Output<string[] | undefined>;
    public readonly repoLayoutRef!: pulumi.Output<string>;
    public readonly snapshotVersionBehavior!: pulumi.Output<string>;
    public readonly suppressPomConsistencyChecks!: pulumi.Output<boolean>;
    public readonly xrayIndex!: pulumi.Output<boolean>;
    public readonly yumRootDepth!: pulumi.Output<number | undefined>;

    /**
     * Create a LocalRepository resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LocalRepositoryArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: LocalRepositoryArgs | LocalRepositoryState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as LocalRepositoryState | undefined;
            inputs["archiveBrowsingEnabled"] = state ? state.archiveBrowsingEnabled : undefined;
            inputs["blackedOut"] = state ? state.blackedOut : undefined;
            inputs["calculateYumMetadata"] = state ? state.calculateYumMetadata : undefined;
            inputs["checksumPolicyType"] = state ? state.checksumPolicyType : undefined;
            inputs["debianTrivialLayout"] = state ? state.debianTrivialLayout : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["dockerApiVersion"] = state ? state.dockerApiVersion : undefined;
            inputs["enableFileListsIndexing"] = state ? state.enableFileListsIndexing : undefined;
            inputs["excludesPattern"] = state ? state.excludesPattern : undefined;
            inputs["forceNugetAuthentication"] = state ? state.forceNugetAuthentication : undefined;
            inputs["handleReleases"] = state ? state.handleReleases : undefined;
            inputs["handleSnapshots"] = state ? state.handleSnapshots : undefined;
            inputs["includesPattern"] = state ? state.includesPattern : undefined;
            inputs["indexCompressionFormats"] = state ? state.indexCompressionFormats : undefined;
            inputs["key"] = state ? state.key : undefined;
            inputs["maxUniqueSnapshots"] = state ? state.maxUniqueSnapshots : undefined;
            inputs["maxUniqueTags"] = state ? state.maxUniqueTags : undefined;
            inputs["notes"] = state ? state.notes : undefined;
            inputs["packageType"] = state ? state.packageType : undefined;
            inputs["propertySets"] = state ? state.propertySets : undefined;
            inputs["repoLayoutRef"] = state ? state.repoLayoutRef : undefined;
            inputs["snapshotVersionBehavior"] = state ? state.snapshotVersionBehavior : undefined;
            inputs["suppressPomConsistencyChecks"] = state ? state.suppressPomConsistencyChecks : undefined;
            inputs["xrayIndex"] = state ? state.xrayIndex : undefined;
            inputs["yumRootDepth"] = state ? state.yumRootDepth : undefined;
        } else {
            const args = argsOrState as LocalRepositoryArgs | undefined;
            if ((!args || args.key === undefined) && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            inputs["archiveBrowsingEnabled"] = args ? args.archiveBrowsingEnabled : undefined;
            inputs["blackedOut"] = args ? args.blackedOut : undefined;
            inputs["calculateYumMetadata"] = args ? args.calculateYumMetadata : undefined;
            inputs["checksumPolicyType"] = args ? args.checksumPolicyType : undefined;
            inputs["debianTrivialLayout"] = args ? args.debianTrivialLayout : undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["dockerApiVersion"] = args ? args.dockerApiVersion : undefined;
            inputs["enableFileListsIndexing"] = args ? args.enableFileListsIndexing : undefined;
            inputs["excludesPattern"] = args ? args.excludesPattern : undefined;
            inputs["forceNugetAuthentication"] = args ? args.forceNugetAuthentication : undefined;
            inputs["handleReleases"] = args ? args.handleReleases : undefined;
            inputs["handleSnapshots"] = args ? args.handleSnapshots : undefined;
            inputs["includesPattern"] = args ? args.includesPattern : undefined;
            inputs["indexCompressionFormats"] = args ? args.indexCompressionFormats : undefined;
            inputs["key"] = args ? args.key : undefined;
            inputs["maxUniqueSnapshots"] = args ? args.maxUniqueSnapshots : undefined;
            inputs["maxUniqueTags"] = args ? args.maxUniqueTags : undefined;
            inputs["notes"] = args ? args.notes : undefined;
            inputs["packageType"] = args ? args.packageType : undefined;
            inputs["propertySets"] = args ? args.propertySets : undefined;
            inputs["repoLayoutRef"] = args ? args.repoLayoutRef : undefined;
            inputs["snapshotVersionBehavior"] = args ? args.snapshotVersionBehavior : undefined;
            inputs["suppressPomConsistencyChecks"] = args ? args.suppressPomConsistencyChecks : undefined;
            inputs["xrayIndex"] = args ? args.xrayIndex : undefined;
            inputs["yumRootDepth"] = args ? args.yumRootDepth : undefined;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(LocalRepository.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering LocalRepository resources.
 */
export interface LocalRepositoryState {
    archiveBrowsingEnabled?: pulumi.Input<boolean>;
    blackedOut?: pulumi.Input<boolean>;
    calculateYumMetadata?: pulumi.Input<boolean>;
    checksumPolicyType?: pulumi.Input<string>;
    debianTrivialLayout?: pulumi.Input<boolean>;
    description?: pulumi.Input<string>;
    dockerApiVersion?: pulumi.Input<string>;
    enableFileListsIndexing?: pulumi.Input<boolean>;
    excludesPattern?: pulumi.Input<string>;
    forceNugetAuthentication?: pulumi.Input<boolean>;
    handleReleases?: pulumi.Input<boolean>;
    handleSnapshots?: pulumi.Input<boolean>;
    includesPattern?: pulumi.Input<string>;
    indexCompressionFormats?: pulumi.Input<pulumi.Input<string>[]>;
    key?: pulumi.Input<string>;
    maxUniqueSnapshots?: pulumi.Input<number>;
    maxUniqueTags?: pulumi.Input<number>;
    notes?: pulumi.Input<string>;
    packageType?: pulumi.Input<string>;
    propertySets?: pulumi.Input<pulumi.Input<string>[]>;
    repoLayoutRef?: pulumi.Input<string>;
    snapshotVersionBehavior?: pulumi.Input<string>;
    suppressPomConsistencyChecks?: pulumi.Input<boolean>;
    xrayIndex?: pulumi.Input<boolean>;
    yumRootDepth?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a LocalRepository resource.
 */
export interface LocalRepositoryArgs {
    archiveBrowsingEnabled?: pulumi.Input<boolean>;
    blackedOut?: pulumi.Input<boolean>;
    calculateYumMetadata?: pulumi.Input<boolean>;
    checksumPolicyType?: pulumi.Input<string>;
    debianTrivialLayout?: pulumi.Input<boolean>;
    description?: pulumi.Input<string>;
    dockerApiVersion?: pulumi.Input<string>;
    enableFileListsIndexing?: pulumi.Input<boolean>;
    excludesPattern?: pulumi.Input<string>;
    forceNugetAuthentication?: pulumi.Input<boolean>;
    handleReleases?: pulumi.Input<boolean>;
    handleSnapshots?: pulumi.Input<boolean>;
    includesPattern?: pulumi.Input<string>;
    indexCompressionFormats?: pulumi.Input<pulumi.Input<string>[]>;
    key: pulumi.Input<string>;
    maxUniqueSnapshots?: pulumi.Input<number>;
    maxUniqueTags?: pulumi.Input<number>;
    notes?: pulumi.Input<string>;
    packageType?: pulumi.Input<string>;
    propertySets?: pulumi.Input<pulumi.Input<string>[]>;
    repoLayoutRef?: pulumi.Input<string>;
    snapshotVersionBehavior?: pulumi.Input<string>;
    suppressPomConsistencyChecks?: pulumi.Input<boolean>;
    xrayIndex?: pulumi.Input<boolean>;
    yumRootDepth?: pulumi.Input<number>;
}
